export default {
  computed: {
    UfTable() {
      return [
        {"value":"AC","text":"ACRE"},
        {"value":"AL","text":"ALAGOAS"},
        {"value":"AM","text":"AMAZONAS"},
        {"value":"AP","text":"AMAPA"},
        {"value":"BA","text":"BAHIA"},
        {"value":"CE","text":"CEARA"},
        {"value":"DF","text":"DISTRITO FEDERAL"},
        {"value":"ES","text":"ESPIRITO SANTO"},
        {"value":"GO","text":"GOIAS"},
        {"value":"MA","text":"MARANHAO"},
        {"value":"MG","text":"MINAS GERAIS"},
        {"value":"MS","text":"MATO GROSSO DO SUL"},
        {"value":"MT","text":"MATO GROSSO"},
        {"value":"PA","text":"PARA"},
        {"value":"PB","text":"PARAIBA"},
        {"value":"PE","text":"PERNAMBUCO"},
        {"value":"PI","text":"PIAUI"},
        {"value":"PR","text":"PARANA"},
        {"value":"RJ","text":"RIO DE JANEIRO"},
        {"value":"RN","text":"RIO GRANDE DO NORTE"},
        {"value":"RO","text":"RONDONIA"},
        {"value":"RR","text":"RORAIMA"},
        {"value":"RS","text":"RIO GRANDE DO SUL"},
        {"value":"SC","text":"SANTA CATARINA"},
        {"value":"SE","text":"SERGIPE"},
        {"value":"SP","text":"SAO PAULO"},
        {"value":"TO","text":"TOCANTINS"}
      ]
    },
    PaisTable() {
      return [
        {"Pais":104,"NomePais":"Afeganistão"},
        {"Pais":105,"NomePais":"Africa do Sul"},
        {"Pais":100,"NomePais":"Albania"},
        {"Pais":87,"NomePais":"Alemanha"},
        {"Pais":106,"NomePais":"Andorra"},
        {"Pais":107,"NomePais":"Angola"},
        {"Pais":108,"NomePais":"Anguilla"},
        {"Pais":200,"NomePais":"Ant.Rep.Iugoslavia Macedonia"},
        {"Pais":109,"NomePais":"Antigua e Barbuda"},
        {"Pais":110,"NomePais":"Antilhas Holandesas"},
        {"Pais":65,"NomePais":"Arabia Saudita"},
        {"Pais":111,"NomePais":"Argelia"},
        {"Pais":56,"NomePais":"Argentina"},
        {"Pais":113,"NomePais":"Aruba"},
        {"Pais":114,"NomePais":"Australia"},
        {"Pais":94,"NomePais":"Austria"},
        {"Pais":77,"NomePais":"Azerbaijão"},
        {"Pais":74,"NomePais":"Bahrein, Ilhas"},
        {"Pais":116,"NomePais":"Bangladesh"},
        {"Pais":117,"NomePais":"Barbados"},
        {"Pais":119,"NomePais":"Belgica"},
        {"Pais":103,"NomePais":"Belize"},
        {"Pais":120,"NomePais":"Benin"},
        {"Pais":121,"NomePais":"Bermudas"},
        {"Pais":122,"NomePais":"Bolivia"},
        {"Pais":124,"NomePais":"Botsuana"},
        {"Pais":55,"NomePais":"Brasil"},
        {"Pais":125,"NomePais":"Brunei"},
        {"Pais":127,"NomePais":"Burkina Faso"},
        {"Pais":128,"NomePais":"Burundi"},
        {"Pais":129,"NomePais":"Butao"},
        {"Pais":131,"NomePais":"Camarões"},
        {"Pais":132,"NomePais":"Camboja"},
        {"Pais":60,"NomePais":"Canadá"},
        {"Pais":66,"NomePais":"Catar"},
        {"Pais":136,"NomePais":"Chade"},
        {"Pais":137,"NomePais":"Chile"},
        {"Pais":138,"NomePais":"Chipre"},
        {"Pais":86,"NomePais":"Cingapura"},
        {"Pais":64,"NomePais":"Colombia"},
        {"Pais":142,"NomePais":"Congo"},
        {"Pais":147,"NomePais":"Costa do Marfim"},
        {"Pais":148,"NomePais":"Costa Rica"},
        {"Pais":67,"NomePais":"Cuba"},
        {"Pais":78,"NomePais":"Dinamarca"},
        {"Pais":80,"NomePais":"Djibuti"},
        {"Pais":82,"NomePais":"Egito"},
        {"Pais":151,"NomePais":"El Salvador"},
        {"Pais":70,"NomePais":"Emirados Arabes Unidos"},
        {"Pais":63,"NomePais":"Equador"},
        {"Pais":152,"NomePais":"Eritreia"},
        {"Pais":155,"NomePais":"Espanha"},
        {"Pais":293,"NomePais":"Est. Da Cidade do Vaticano"},
        {"Pais":58,"NomePais":"Estados Unidos"},
        {"Pais":157,"NomePais":"Etiopia"},
        {"Pais":158,"NomePais":"Falkland (Ilhas Malvinas)"},
        {"Pais":160,"NomePais":"Fiji"},
        {"Pais":161,"NomePais":"Filipinas"},
        {"Pais":162,"NomePais":"Finlandia"},
        {"Pais":163,"NomePais":"Formosa (Taiwan)"},
        {"Pais":90,"NomePais":"França"},
        {"Pais":101,"NomePais":"Gabao"},
        {"Pais":164,"NomePais":"Gambia"},
        {"Pais":165,"NomePais":"Gana"},
        {"Pais":75,"NomePais":"Geórgia"},
        {"Pais":166,"NomePais":"Gibraltar"},
        {"Pais":167,"NomePais":"Granada"},
        {"Pais":168,"NomePais":"Grecia"},
        {"Pais":169,"NomePais":"Groenlandia"},
        {"Pais":170,"NomePais":"Guadalupe"},
        {"Pais":171,"NomePais":"Guam"},
        {"Pais":172,"NomePais":"Guatemala"},
        {"Pais":174,"NomePais":"Guiana"},
        {"Pais":175,"NomePais":"Guiana Francesa"},
        {"Pais":176,"NomePais":"Guiné"},
        {"Pais":177,"NomePais":"Guiné-Bissau"},
        {"Pais":178,"NomePais":"Guiné-Equatorial"},
        {"Pais":179,"NomePais":"Haiti"},
        {"Pais":62,"NomePais":"Holanda"},
        {"Pais":180,"NomePais":"Honduras"},
        {"Pais":69,"NomePais":"Hong Kong"},
        {"Pais":81,"NomePais":"Iêmen"},
        {"Pais":139,"NomePais":"Ilha (Navidad) Chirstmas"},
        {"Pais":202,"NomePais":"Ilha da Madeira"},
        {"Pais":208,"NomePais":"Ilha de Man"},
        {"Pais":173,"NomePais":"Ilha do Canal Guernsey"},
        {"Pais":188,"NomePais":"Ilha do Canal Jersey"},
        {"Pais":150,"NomePais":"Ilha Dominica"},
        {"Pais":231,"NomePais":"Ilha Niue"},
        {"Pais":232,"NomePais":"Ilha Norfolk"},
        {"Pais":242,"NomePais":"Ilha Pitcairn"},
        {"Pais":251,"NomePais":"Ilha Reunião"},
        {"Pais":297,"NomePais":"Ilha Wake"},
        {"Pais":115,"NomePais":"Ilhas Bahamas"},
        {"Pais":133,"NomePais":"Ilhas Canarias"},
        {"Pais":134,"NomePais":"Ilhas Cayman"},
        {"Pais":140,"NomePais":"Ilhas Cocos (Keeling)"},
        {"Pais":141,"NomePais":"Ilhas Comores"},
        {"Pais":144,"NomePais":"Ilhas Cook"},
        {"Pais":236,"NomePais":"Ilhas do Pacifico"},
        {"Pais":159,"NomePais":"Ilhas Feroe"},
        {"Pais":189,"NomePais":"Ilhas Johnston"},
        {"Pais":211,"NomePais":"Ilhas Marshall"},
        {"Pais":218,"NomePais":"Ilhas Midway"},
        {"Pais":224,"NomePais":"Ilhas Montserrat"},
        {"Pais":256,"NomePais":"Ilhas Salomão"},
        {"Pais":262,"NomePais":"Ilhas São Cristóvão e Neves"},
        {"Pais":264,"NomePais":"Ilhas São Tomé e Principe"},
        {"Pais":283,"NomePais":"Ilhas Toquelau"},
        {"Pais":286,"NomePais":"Ilhas Turcas e Caicos"},
        {"Pais":295,"NomePais":"Ilhas Virgens (Britanicas)"},
        {"Pais":296,"NomePais":"Ilhas Virgens (E.U.A.)"},
        {"Pais":182,"NomePais":"India"},
        {"Pais":183,"NomePais":"Indonesia"},
        {"Pais":71,"NomePais":"Iraque"},
        {"Pais":95,"NomePais":"Irlanda"},
        {"Pais":102,"NomePais":"Islandia"},
        {"Pais":185,"NomePais":"Israel"},
        {"Pais":92,"NomePais":"Italia"},
        {"Pais":186,"NomePais":"Jamaica"},
        {"Pais":187,"NomePais":"Japão"},
        {"Pais":73,"NomePais":"Jordânia"},
        {"Pais":190,"NomePais":"Kiribati"},
        {"Pais":68,"NomePais":"Kuwait"},
        {"Pais":192,"NomePais":"Lesoto"},
        {"Pais":79,"NomePais":"Libano"},
        {"Pais":194,"NomePais":"Liberia"},
        {"Pais":195,"NomePais":"Libia"},
        {"Pais":196,"NomePais":"Liechtenstein"},
        {"Pais":198,"NomePais":"Luxemburgo"},
        {"Pais":199,"NomePais":"Macau"},
        {"Pais":201,"NomePais":"Madagascar"},
        {"Pais":203,"NomePais":"Malasia"},
        {"Pais":204,"NomePais":"Malavi"},
        {"Pais":205,"NomePais":"Maldivas"},
        {"Pais":206,"NomePais":"Mali"},
        {"Pais":207,"NomePais":"Malta"},
        {"Pais":209,"NomePais":"Marianas do Norte"},
        {"Pais":210,"NomePais":"Marrocos"},
        {"Pais":212,"NomePais":"Martinica"},
        {"Pais":213,"NomePais":"Mauricio"},
        {"Pais":214,"NomePais":"Mauritania"},
        {"Pais":215,"NomePais":"México"},
        {"Pais":216,"NomePais":"Mianmar (Birmania)"},
        {"Pais":217,"NomePais":"Micronesia"},
        {"Pais":219,"NomePais":"Moçambique"},
        {"Pais":221,"NomePais":"Monaco"},
        {"Pais":222,"NomePais":"Mongolia"},
        {"Pais":223,"NomePais":"Montenegro"},
        {"Pais":225,"NomePais":"Namibia"},
        {"Pais":226,"NomePais":"Nauru"},
        {"Pais":227,"NomePais":"Nepal"},
        {"Pais":228,"NomePais":"Nicaragua"},
        {"Pais":229,"NomePais":"Niger"},
        {"Pais":230,"NomePais":"Nigeria"},
        {"Pais":233,"NomePais":"Noruega"},
        {"Pais":234,"NomePais":"Nova Caledonia"},
        {"Pais":235,"NomePais":"Nova Zelandia"},
        {"Pais":76,"NomePais":"Omã"},
        {"Pais":237,"NomePais":"Palau"},
        {"Pais":238,"NomePais":"Panamá"},
        {"Pais":239,"NomePais":"Papua Nova Guiné"},
        {"Pais":240,"NomePais":"Paquistão"},
        {"Pais":59,"NomePais":"Paraguai"},
        {"Pais":241,"NomePais":"Peru"},
        {"Pais":243,"NomePais":"Polinesia Francesa"},
        {"Pais":245,"NomePais":"Porto Rico"},
        {"Pais":246,"NomePais":"Portugal"},
        {"Pais":247,"NomePais":"Quenia"},
        {"Pais":89,"NomePais":"Reino Unido"},
        {"Pais":191,"NomePais":"Rep.Pop.Democr. Do Laos"},
        {"Pais":145,"NomePais":"Rep.Pop.Democrática Coreia"},
        {"Pais":277,"NomePais":"Rep.Unida da Tanzania"},
        {"Pais":269,"NomePais":"Republica Arabe da Siria"},
        {"Pais":249,"NomePais":"Republica Centro-Africana"},
        {"Pais":112,"NomePais":"Republica da Armenia"},
        {"Pais":123,"NomePais":"Republica da Bosnia-Herzegovina"},
        {"Pais":126,"NomePais":"Republica da Bulgaria"},
        {"Pais":146,"NomePais":"Republica da Coreia"},
        {"Pais":149,"NomePais":"Republica da Croácia"},
        {"Pais":154,"NomePais":"Republica da Eslovenia"},
        {"Pais":156,"NomePais":"Republica da Estonia"},
        {"Pais":181,"NomePais":"Republica da Hungria"},
        {"Pais":193,"NomePais":"Republica da Letonia"},
        {"Pais":197,"NomePais":"Republica da Lituania"},
        {"Pais":220,"NomePais":"Republica da Moldavia"},
        {"Pais":244,"NomePais":"Republica da Polonia"},
        {"Pais":130,"NomePais":"Republica de Cabo Verde"},
        {"Pais":143,"NomePais":"Republica Democrática do Congo"},
        {"Pais":135,"NomePais":"Republica do Cazaquistão"},
        {"Pais":275,"NomePais":"Republica do Tadjiquistão"},
        {"Pais":287,"NomePais":"Republica do Turcomenistão"},
        {"Pais":291,"NomePais":"Republica do Uzbequistão"},
        {"Pais":250,"NomePais":"Republica Dominicana"},
        {"Pais":153,"NomePais":"Republica Eslovaca"},
        {"Pais":184,"NomePais":"Republica Islamica do Irã"},
        {"Pais":85,"NomePais":"República Popular da China"},
        {"Pais":248,"NomePais":"Republica Quirguiz"},
        {"Pais":278,"NomePais":"Republica Tcheca"},
        {"Pais":118,"NomePais":"Republida da Belarus"},
        {"Pais":252,"NomePais":"Romenia"},
        {"Pais":253,"NomePais":"Ruanda"},
        {"Pais":91,"NomePais":"Russia"},
        {"Pais":254,"NomePais":"Saara Ocidental"},
        {"Pais":255,"NomePais":"Saint Kitts e Nevis"},
        {"Pais":257,"NomePais":"Samoa"},
        {"Pais":258,"NomePais":"Samoa Americana"},
        {"Pais":259,"NomePais":"San marino"},
        {"Pais":260,"NomePais":"Santa Helena"},
        {"Pais":261,"NomePais":"Santa Lucia"},
        {"Pais":263,"NomePais":"São Pedro e Miguelon"},
        {"Pais":265,"NomePais":"São Vicente e Granadinas"},
        {"Pais":266,"NomePais":"Senegal"},
        {"Pais":98,"NomePais":"Serra Leoa"},
        {"Pais":267,"NomePais":"Servia"},
        {"Pais":268,"NomePais":"Seychelles"},
        {"Pais":270,"NomePais":"Somalia"},
        {"Pais":271,"NomePais":"Sri Lanka"},
        {"Pais":272,"NomePais":"Suazilandia"},
        {"Pais":88,"NomePais":"Sudão"},
        {"Pais":273,"NomePais":"Suecia"},
        {"Pais":61,"NomePais":"Suíça"},
        {"Pais":274,"NomePais":"Suriname"},
        {"Pais":276,"NomePais":"Tailandia"},
        {"Pais":279,"NomePais":"Territorio Brit. Oc. Indico"},
        {"Pais":280,"NomePais":"Timor Leste"},
        {"Pais":281,"NomePais":"Togo"},
        {"Pais":282,"NomePais":"Tonga"},
        {"Pais":284,"NomePais":"Trinidad e Tobago"},
        {"Pais":285,"NomePais":"Tunista"},
        {"Pais":84,"NomePais":"Turquia"},
        {"Pais":288,"NomePais":"Tuvalu"},
        {"Pais":289,"NomePais":"Ucrania"},
        {"Pais":290,"NomePais":"Uganda"},
        {"Pais":57,"NomePais":"Uruguai"},
        {"Pais":292,"NomePais":"Vanuatu"},
        {"Pais":294,"NomePais":"Venezuela"},
        {"Pais":72,"NomePais":"Vietnã"},
        {"Pais":298,"NomePais":"Zambia"},
        {"Pais":299,"NomePais":"Zimbabue"},
        {"Pais":300,"NomePais":"Zona do Canal do Panamá"}        
      ]
    },
    TipoPessoaTable() {
      return [
        {"value":1,"text":"Pessoa Física"},
        {"value":2,"text":"Pessoa Jurídica"}
      ]
    },
    StatusPessoaTable() {
      return [
        {"value":1,"text":"Cadastro Regular"},
        {"value":2,"text":"Cadastro Irregular"},
        {"value":3,"text":"Cadastro Desativado"}
      ]
    },
    StatusFiscalTable() {
      return [
        {"value":1,"text":"Sem Restrições"},
        {"value":2,"text":"Restrição na Receita Federal"},
        {"value":3,"text":"Restrição na Receita Estadual"}
      ]
    },
    TipoRegimeTribTable() {
      return [
        {"value":1,"text":"Simples Nacional"},
        {"value":2,"text":"Simples Nacional - Excesso de sublimite de receita bruta"},
        {"value":3,"text":"Regime Normal"}
      ]
    }
  }
}
